name: Deploy React Frontend to HomeServer

# 언제 실행할지
on:
  push:
    branches: [ main ]  # main 브랜치에 푸시될 때마다 실행
  workflow_dispatch:

env:
  DOCKERHUB_NAMESPACE: shinhs6384
  IMAGE_TAG: ${{ github.sha }}
  HOME_HOST: ${{ secrets.HOME_HOST }}
  HOME_USER: ${{ secrets.HOME_USER }}
  HOME_PASSWORD: ${{ secrets.HOME_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # 깃허브가 제공하는 리눅스 서버에서 실행

    steps:
      # 현재 레포지토리 코드 가져오기
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        run : |
          docker build -f Dockerfile -t ${{ env.DOCKERHUB_NAMESPACE }}/frontend:${{ env.IMAGE_TAG }} .
          docker push ${{ env.DOCKERHUB_NAMESPACE }}/frontend:${{ env.IMAGE_TAG }}
          docker tag ${{ env.DOCKERHUB_NAMESPACE }}/frontend:${{ env.IMAGE_TAG }} ${{ env.DOCKERHUB_NAMESPACE }}/frontend:latest
          docker push ${{ env.DOCKERHUB_NAMESPACE }}/frontend:latest

  deploy:
    name: Deploy to HomeServer
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH into HomeServer and run deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ env.HOME_HOST }}
          port: 4242
          username: ${{ env.HOME_USER }}
          password: ${{ env.HOME_PASSWORD }}
          script: |
            cd /home/hyeongsh/betterlife
            docker compose -p betterlife -f docker-compose.infra.yml pull frontend
            docker compose -p betterlife -f docker-compose.infra.yml up -d frontend
